steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Image Build
    args: ['build', '-t', 'docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/flask-image', './app']

  - name: 'gcr.io/cloud-builders/docker'
    id: Image Push to Artifact Registry
    args: ['push', 'docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/flask-image']

# images:
#   - 'gcr.io/$PROJECT_ID/flask-image'

substitutions:
  _REPO_NAME: flask-app # Default value

options:
  logging: CLOUD_LOGGING_ONLY
