steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Image Build
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_REPO_NAME:$SHORT_SHA', './app']

  - name: 'gcr.io/cloud-builders/docker'
    id: Image Push to Artifact Registry
    args: ['push', 'gcr.io/$PROJECT_ID/$_REPO_NAME:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud deploy releases create release-$SHORT_SHA \
          --project=$PROJECT_ID \
          --region=$REGION \
          --delivery-pipeline=$PIPELINE_NAME \
          --images=my-app=$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME:$SHORT_SHA

images:
  - 'gcr.io/$PROJECT_ID/$_REPO_NAME:$SHORT_SHA'
#$PROJECT_ID/$_REPO_NAME:$SHORT_SHA
options:
  logging: CLOUD_LOGGING_ONLY
  
substitutions:
  #  _LOCATION: us-central1
  _REPO_NAME: flask-app # Default value
  _APP_NAME: flask-app
  _REGION: us-central1
  _PIPELINE_NAME: my-pipeline



