apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-pipeline
description: "My GKE DEPLOY pipeline"
serialPipeline:
  stages:
    - targetId: flask-pipeline

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: flask-pipeline
description: "Development environment"
requireApproval: false
gke:
  cluster: projects/$PROJECT_ID/locations/us-central1/clusters/terra-gke-cluster
  location: us-central1
