steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Image Build
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app', './app']

  - name: 'gcr.io/cloud-builders/docker'
    id: Image Push to Artifact Registry
    args: ['push', 'gcr.io/$PROJECT_ID/flask-app',]

images:
  - 'gcr.io/$PROJECT_ID/flask-app'

substitutions:
  _LOCATION: us-central1
  _REPO_NAME: flask-app # Default value

options:
  logging: CLOUD_LOGGING_ONLY

#us-central1-docker.pkg.dev/gke-k8-terra/webapp
