steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Image Build
    args: ['build', '-t', '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME', './app']

  - name: 'gcr.io/cloud-builders/docker'
    id: Image Push to Artifact Registry
    args: ['push', '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME']

# images:
#   - 'gcr.io/$PROJECT_ID/flask-image'

substitutions:
  _LOCATION: us-central1
  _REPO_NAME: flask-app # Default value

options:
  logging: CLOUD_LOGGING_ONLY

#us-central1-docker.pkg.dev/gke-k8-terra/webapp
