steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build-push-flask-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Building Docker image"
        docker build -t gcr.io/$PROJECT_ID/$_REPO_NAME:$SHORT_SHA ./app
        docker push gcr.io/$PROJECT_ID/$_REPO_NAME:$SHORT_SHA
    
  #   args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_REPO_NAME:$SHORT_SHA', './app']

  # - name: 'gcr.io/cloud-builders/docker'
  #   id: Image Push to Artifact Registry
  #   args: ['push', 'gcr.io/$PROJECT_ID/$_REPO_NAME:$SHORT_SHA']

  # - name: 'gcr.io/cloud-builders/skaffold'
  #   args: ['deploy', '-f', 'skaffold.yaml', '--default-repo', 'gcr.io/$PROJECT_ID/$_REPO_NAME', '--images', 'gcr.io/$PROJECT_ID/$_REPO_NAME:$SHORT_SHA']


  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: 'Cloud-deploy'
    waitFor: ['Build-push-flask-image']
    entrypoint: bash
    args: 
      - '-c'
      - gcloud deploy releases create $_BUILD_NAME-${SHORT_SHA} --project=$PROJECT_ID --region=$_REGION --delivery-pipeline=$_PIPELINE_NAME --skaffold-file=./skaffold.yaml
   
images:
  - 'gcr.io/$PROJECT_ID/$_REPO_NAME:$SHORT_SHA'
#$PROJECT_ID/$_REPO_NAME:$SHORT_SHA
options:
  logging: CLOUD_LOGGING_ONLY
  
substitutions:
  #  _LOCATION: us-central1
  _REPO_NAME: flask-app # Default value
  _APP_NAME: flask-app
  _REGION: us-central1
  _PIPELINE_NAME: my-pipeline
  _TAG: '$SHORT_SHA'



