# apiVersion: skaffold/v2beta13
# kind: Config
# metadata:
#   name: flask-app
# build:
#   artifacts:
#   - image: gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA
# deploy:
#   kubectl:
#     manifests:
#     - k8s/deployment.yaml

apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: flask-app
profiles:
  - name: flask-pipeline
    build:
      artifacts:
        - image: gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA
    deploy:
      kubectl:
        manifests:
          - k8s/deployment.yaml
