apiVersion: skaffold/v4beta9
kind: Config
profiles:
  - name: flask-pipeline
    build:
      tagPolicy:
        gitCommit: {}
      local: {}
    manifests:
      rawYaml:
        - ./k8s/*
    deploy:
      kubectl: {}
      logs:
        prefix: container


# apiVersion: skaffold/v2beta26
# kind: Config
# apiVersion: skaffold/v4beta7
# kind: Config
# build:
#   tagPolicy:
#     gitCommit: {}
#   local: {}
# profiles: # used to differentiate the manifest files for dev and prod env.
#   - name: flask-pipeline # used in cloud-deploy.yaml of step-1.
#     manifests:
#     - k8s/deployment.yaml
