apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: flask-app
build:
  artifacts:
  - image: gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
