apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: flask-app
build:
  artifacts:
    - image: gcr.io/gke-k8-terra/flask-app
      context: .
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml

# apiVersion: skaffold/v2beta13
# kind: Config
# metadata:
#   name: flask-app
# build:
#   artifacts:
#   - image: gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA
# deploy:
#   kubectl:
#     manifests:
#     - k8s/deployment.yaml

# apiVersion: skaffold/v2beta25
# kind: Config
# metadata:
#   name: python-app
# build:
#   artifacts:
#     - image: us-west1-docker.pkg.dev/YOUR_PROJECT_ID/YOUR_REPOSITORY_NAME/python-app
#       context: .
#       docker:
#         dockerfile: Dockerfile
#   tagPolicy:
#     sha256: {}
# deploy:
#   kubectl:
#     manifests:
#       - k8s/deployment.yaml
#       - k8s/service.yaml
